### ISSUE TITLE
'Disease state'

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#6]
Mark Phillips says: 

> Disease state: to refer to existing ontologies.  The question is how much to contain.  SNOMED, ICD-10 and ICD-O have a lot of fine detail but are not ontologies.  Which ontology does the best of defining the basic cancer class?  Can we constrain instances to come from certain value sets or is that too prescriptive for an ontology?

We should try to use the human disease ontology: http://disease-ontology.org/

Mark, can you explain more about exactly what is meant by 'disease state' here?

**Comment by Bayesianworld** [comment]
This is very interesting.  The disease ontology looks very clean and straightforward which is good.  However, their classes align more with ICD-0 categories which are not used all that much in rad onc (though perhaps they should be).  ICD-10 mixes the type of tumor with the organ, e.g. adenocarcinoma of the prostate.  So this highlights the differences between an ontology and a vocabulary (however rooted in theory).  My first thought is that this doesn't matter--however, as our first assignment is to respond to the ASTRO MDE and synoptic data, we will need the combination of site and tumor type.  I think we can build up the necessary object through the disease-ontology definition and the anatomic site, though I am not sure of that.  Maybe Peter and Chuck can help clarify to what extent the end products need to match industry-type standards such as ICD10.

By disease state, I was referring to the types of data that are usually associated with a treatment:
   (a) type of tumor), (b) location of tumor, (c) stage and/or grade, (d) primary or secondary.  All of these variables have a strong influence on the intent, treatment given and the outcome expected.

**Comment by Bayesianworld** [comment]
I take back what I just said about the disease ontology.  Seems that I was looking at a very narrow view.  There is a tutorial at the website that helps show how to explore it.  In any case, their description of cancers seems much closer to what I think we need.  See what you think....

**Comment by andredekker** [comment]
Looking at the disease ontology I find its semantics are not complete - i guess because of OBO forcing just a single parent. E.g. a lung_adenocarcinoma is_a lung_cancer but it is also an adenocarcinoma which is not asserted. Strangely and incorrectly it is not a subclass of non-small cell lung cancer/NSCLC (while e.g. lung squamous cell carcinoma is defined as NSCLC). The OBO edition of NCIT ([http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C2926]) is much more expressive. E.g. it defines Lung Adenocarcinoma as an equivalent class to {Non-Small Cell Adenocarcinoma and Lung Non-Small Cell Carcinoma}. 

BTW NCIT also has the property Disease_Has_Primary_Anatomic_Site which is what we need for metastatic disease like a lung cancer metastasis found in the brain....

**Comment by jonathanbona** [comment]
<img width="1429" alt="Screen Shot 2020-02-12 at 10 53 13 AM" src="https://user-images.githubusercontent.com/78007/74357717-ea976180-4d85-11ea-9ca9-53e2d40f8673.png">

**Comment by andredekker** [comment]
We decided to use the disease ontology, so closing
